kind: PersistentVolume
apiVersion: v1
metadata:
  name: alertmanager-db 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: alertmanager-doks-cluster-monitoring-pr-alertmanager-db-alertmanager-doks-cluster-monitoring-pr-alertmanager-0 
    namespace: monitoring
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/repo/storage-monitoring/prometheus-db"
