kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-db 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: doks-cluster-monitoring-grafana 
    namespace: monitoring
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/repo/storage-monitoring/grafana"
