kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: prometheus-doks-cluster-monitoring-pr-prometheus-db-prometheus-doks-cluster-monitoring-pr-prometheus-0 
    namespace: monitoring
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/repo/storage-monitoring/prometheus-db"
